# Generated by Django 5.1.3 on 2025-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary', '0002_categorymodel_bookmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
